<h1><center>Introduction to Scientific Computing, Practical Markov Chains</center></h1>

<h4>Sebastian Preststulen (S4270754), Dominic Therattil (S4228952)</h2>
<h4>Date handed in: March 14, 2022</h2>
<h4>Assignment 3 - PageRank </h2>

In this assignment, the aim is to implement the PageRank algorithm, and analyze the effect of teleporting factor on the output of the algorithm.

### Importing necessary packages

In [66]:
# if you have already installed numpy and matplotlib, you can skip the next two lines
# pip install matplotlib
# pip install numpy

import numpy as np
from numpy import linalg as LA
import matplotlib.pyplot as plt

In [67]:
# constructing the connectivity matrix
A = np.array([[1,1,0],[1,0,1],[0,0,1]])

## Implementing the elements of the PageRank algorithm


In order to perform the algorithm, we define the following functions:
- normalize_conn_matrix: computing the transition probability from the connecting matrix,
- appr_stationary: compute the stationary distribution, based on x(t) = x(t-1) . T,
- dead_end: to prevent dead end problem,
- teleporting_factor: to resolve spider trap, 

Hint. you may use "np.matmul" function for the matrix multiplication.

In [68]:
def normalize_conn_matrix(A):
    """
    A: (n*n) connectivity matrix
    T: transition probabilities
    """
    T = A.astype(np.float64).copy()
    for i in range(len(A)):
        T[i] = T[i]/sum(A[i])
    
    return T

In [69]:
# Test your code
T = normalize_conn_matrix(A)
print(T)

print("\n Expected solution:")
print("[[0.5 0.5 0. ] \n [0.5 0.  0.5] \n [0.  0.  1. ]]")

[[0.5 0.5 0. ]
 [0.5 0.  0.5]
 [0.  0.  1. ]]

 Expected solution:
[[0.5 0.5 0. ] 
 [0.5 0.  0.5] 
 [0.  0.  1. ]]


In [70]:
def appr_stationary(T, maxiter=20):
    """
    T: transition probability,
    maxiter: number of steps
    x_m: the state vector
    """
    x_m = np.repeat(1.0/len(T), len(T))

    for i in range(maxiter):
        x_m = np.matmul(x_m, T)

    return x_m

In [71]:
# Test your code
st_dist = appr_stationary(T, maxiter=20)
print(st_dist)

print("\n Expected solution:")
print("[0.00563018 0.00347964 0.99089019]")


[0.00563018 0.00347964 0.99089019]

 Expected solution:
[0.00563018 0.00347964 0.99089019]


In [72]:
def dead_end(A):
    """
    A: connecting matrix
    A_new: connecting matrix by resolving the dead end problem
    """
    A_new = A.copy()
    for i in range(len(A)):
        if (sum(A[i]) == 0):
            A_new[i] = np.repeat(1.0, len(A))
    
    return A_new

In [73]:
print(dead_end(A))

print("\n Expected output:")
print("[[1 1 0] \n [1 0 1] \n [0 0 1]]")

[[1 1 0]
 [1 0 1]
 [0 0 1]]

 Expected output:
[[1 1 0] 
 [1 0 1] 
 [0 0 1]]


In [74]:
def teleporting_factor(T, alpha=0.9):
    """
    T: transition probability,
    alpha: teleporting factor.
    T_new: transition probability after implementing teleporting factor
    """
    T_new = T.copy()
    T_new = alpha * T_new + (1 - alpha) * 1/len(T_new)

    return T_new

In [75]:
print(teleporting_factor(dead_end(T)))

print("\n Expected output:")
print("[[0.48333333 0.48333333 0.03333333] \n [0.48333333 0.03333333 0.48333333] \n [0.03333333 0.03333333 0.93333333]]")

[[0.48333333 0.48333333 0.03333333]
 [0.48333333 0.03333333 0.48333333]
 [0.03333333 0.03333333 0.93333333]]

 Expected output:
[[0.48333333 0.48333333 0.03333333] 
 [0.48333333 0.03333333 0.48333333] 
 [0.03333333 0.03333333 0.93333333]]


## PageRank algorithm 

Here, we use the functions, defined above, to perform PageRank algorithm.
   1) resolve the dead end problem,<br>
   2) compute the transition probability, <br>
   3) use teleporting factor to prevent spider trap,<br>
   4) compute the stationary distribuion.<br>

In [76]:
def PageRank(A, alpha=0.8, maxiter=20):
    """
    A: connectivity matrix,
    alpha: teleporting factor,
    maxiter: number of steps (for approximating stationary distribution)
    st_dist: an approximation for the stationary distribution 
    """
    # Insert your code here
    newA = dead_end(A)
    T = normalize_conn_matrix(newA)
    T_new = teleporting_factor(T, alpha)
    st_dist = appr_stationary(T_new, maxiter)
    
    return st_dist

In [77]:
print(PageRank(A, 0.9, 30))

print("\n Expected output:")
print("[[0.13910008 0.09593028 0.76496964]]")

[0.13910685 0.09593446 0.76495869]

 Expected output:
[[0.13910008 0.09593028 0.76496964]]


<h1><center>Analyzing PageRank algorithm</center></h1>

<h2>Performing PageRank algorithm on the following network </h2>

![Cat](graph.png)

In the following, please perform:

- Performing PageRank algorithm on the network,
- Investigating the effect of teleporting 

### 1) Perform PageRank algorithm

Apply PageRank on the network (alpha = 0.85), and report the pageranks,
   1) Construct the connectivity matrix, <br>
   2) Apply PageRank algorithm (i.e. function "PageRank")

In [80]:
arr = np.array(
[[0,0,0,0,0,0,0,0,0,0,0],#a
[0,0,1,0,0,0,0,0,0,0,0], #b
[0,1,0,0,0,0,0,0,0,0,0], #c
[1,1,0,0,0,0,0,0,0,0,0], #d
[0,1,0,1,0,1,0,0,0,0,0], #e
[0,1,0,0,1,0,0,0,0,0,0], #f
[0,1,0,0,1,0,0,0,0,0,0], #g
[0,1,0,0,1,0,0,0,0,0,0], #h
[0,1,0,0,1,0,0,0,0,0,0], #l
[0,0,0,0,1,0,0,0,0,0,0], #m
[0,0,0,0,1,0,0,0,0,0,0]] #n 
)

print(PageRank(arr, 0.85, 30))

[0.03278149 0.38359681 0.34371442 0.03908709 0.08088569 0.03908709
 0.01616948 0.01616948 0.01616948 0.01616948 0.01616948]


### 2) The effect of spider trap

In order to see the effect of spider trap on the output, please perform PageRank algorithm with different alpha values. <br>
Run the algorithm with alpha = 1 (corresponding to not using the teleporting factor):<br>
    - compare its output with alpha = 0.85, <br>
    - please discuss the effect of teleporting factor on the stationary distribution. 
    

In [83]:
# Insert your code here
print("PageRank when alpha = 1:", PageRank(arr, 1, 30), "\n")
print("PageRank when alpha = 0.85:", PageRank(arr, 0.85, 30))

PageRank when alpha = 1: [1.65124104e-07 3.85320722e-01 6.14678315e-01 1.88864442e-07
 2.95148105e-07 1.88864442e-07 2.48884102e-08 2.48884102e-08
 2.48884102e-08 2.48884102e-08 2.48884102e-08] 

PageRank when alpha = 0.85: [0.03278149 0.38359681 0.34371442 0.03908709 0.08088569 0.03908709
 0.01616948 0.01616948 0.01616948 0.01616948 0.01616948]


2 ) </br>
When we are setting alpha as 1, we are not utilizing our teleporting factor because alpha is 1. Since we are not using this, we get a stationary distribution that is very low. We also know that it is wrong, since the sum of the distribution does not equal to 1. When we set alpha to 0.85 (which minimally increases probability to reach other nodes that can't be reached), we get a stationary distribution which is much more accurate and correct. Thus, using an appropriate value for alpha when implementing the teleporting factor is necessary in order to get the accurate results for the stationary distribution.

Contribution: </br>
We worked on the assignment collaboratively over a call, helping each other as we got stuck and talking through ideas. </br>
Program Design: 50/50 </br>
Program Implementation: 50/50 </br>
Answering questions posed: 50/50 </br>
Writing the report: 50/50